name: Node-scan
on:
  schedule:
    - cron: '00 5 * * *'
  push:
    branches: ["master"]
    paths:
      - 'docker/**'
  pull_request:
    branches: ["master"]
    paths:
      - 'docker/**'

env:
  IMAGE_NAME: "node-scan"
  VERSION: "latest"

jobs:
  test:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Build test
        run: |
          docker build -t tst:${VERSION} -f docker/Dockerfile .
          docker run -i --rm tst:${VERSION} 8.8.8.8 53 > check.txt
          docker rmi tst:{VERSION}
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: RootShell-coder
          author_email: Root.Shelling@gmail.com
          message: 'upd'
          add: 'check*'

  push:
    needs: [ test ]
    name: Publish to Docker Hub
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: |
          docker build -f Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:${GITHUB_SHA::5} -f docker/Dockerfile .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:${GITHUB_SHA::5} ${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:{VERSION}
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Push Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:${GITHUB_SHA::5}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:{VERSION}
      - name: Delete images
        run: |
          docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:${GITHUB_SHA::5}
          docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:{VERSION}
